config/routes.rb
Rails.application.routes.draw do
  resources :fruits
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "fruits#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: %i[ show edit update destroy ]

  # GET /fruits or /fruits.json
  def index
    @fruits = Fruit.all
  end

  # GET /fruits/1 or /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits or /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to fruit_url(@fruit), notice: "Fruit was successfully created." }
        format.json { render :show, status: :created, location: @fruit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1 or /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to fruit_url(@fruit), notice: "Fruit was successfully updated." }
        format.json { render :show, status: :ok, location: @fruit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1 or /fruits/1.json
  def destroy
    @fruit.destroy

    respond_to do |format|
      format.html { redirect_to fruits_url, notice: "Fruit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fruit_params
      params.require(:fruit).permit(:title, :headline, :image, :gradient_dark, :gradient_light, :description, :energy, :sugar, :fat, :protein, :vitamins, :minerals)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/views/fruits/_form.html.erb
<%= form_with(model: fruit) do |form| %>
  <% if fruit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
        <% fruit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :headline, style: "display: block" %>
    <%= form.text_field :headline %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :gradient_dark, style: "display: block" %>
    <%= form.text_field :gradient_dark %>
  </div>

  <div>
    <%= form.label :gradient_light, style: "display: block" %>
    <%= form.text_field :gradient_light %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :energy, style: "display: block" %>
    <%= form.text_field :energy %>
  </div>

  <div>
    <%= form.label :sugar, style: "display: block" %>
    <%= form.text_field :sugar %>
  </div>

  <div>
    <%= form.label :fat, style: "display: block" %>
    <%= form.text_field :fat %>
  </div>

  <div>
    <%= form.label :protein, style: "display: block" %>
    <%= form.text_field :protein %>
  </div>

  <div>
    <%= form.label :vitamins, style: "display: block" %>
    <%= form.text_field :vitamins %>
  </div>

  <div>
    <%= form.label :minerals, style: "display: block" %>
    <%= form.text_field :minerals %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fruits/_fruit.html.erb
<div id="<%= dom_id fruit %>">
  <p>
    <strong>Title:</strong>
    <%= fruit.title %>
  </p>

  <p>
    <strong>Headline:</strong>
    <%= fruit.headline %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= fruit.image %>
  </p>

  <p>
    <strong>Gradient dark:</strong>
    <%= fruit.gradient_dark %>
  </p>

  <p>
    <strong>Gradient light:</strong>
    <%= fruit.gradient_light %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= fruit.description %>
  </p>

  <p>
    <strong>Energy:</strong>
    <%= fruit.energy %>
  </p>

  <p>
    <strong>Sugar:</strong>
    <%= fruit.sugar %>
  </p>

  <p>
    <strong>Fat:</strong>
    <%= fruit.fat %>
  </p>

  <p>
    <strong>Protein:</strong>
    <%= fruit.protein %>
  </p>

  <p>
    <strong>Vitamins:</strong>
    <%= fruit.vitamins %>
  </p>

  <p>
    <strong>Minerals:</strong>
    <%= fruit.minerals %>
  </p>

</div>

app/views/fruits/edit.html.erb
<h1>Editing fruit</h1>

<%= render "form", fruit: @fruit %>

<br>

<div>
  <%= link_to "Show this fruit", @fruit %> |
  <%= link_to "Back to fruits", fruits_path %>
</div>

app/views/fruits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fruits</h1>

<div id="fruits">
  <% @fruits.each do |fruit| %>
    <%= render fruit %>
    <p>
      <%= link_to "Show this fruit", fruit %>
    </p>
  <% end %>
</div>

<%= link_to "New fruit", new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New fruit</h1>

<%= render "form", fruit: @fruit %>

<br>

<div>
  <%= link_to "Back to fruits", fruits_path %>
</div>

app/views/fruits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fruit %>

<div>
  <%= link_to "Edit this fruit", edit_fruit_path(@fruit) %> |
  <%= link_to "Back to fruits", fruits_path %>

  <%= button_to "Destroy this fruit", @fruit, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruits</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>